app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/comment/<int:pk>/', views.create_comment, name='comment_create')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models


class Diary(models.Model):
    text = models.TextField('diary')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
  
        def __str__(self):
            return self.title


class Comment(models.Model):
    text = models.CharField('comment', max_length=300)
    target = models.ForeignKey(Diary, on_delete=models.CASCADE, verbose_name='related diary')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
  
        def __str__(self):
            return self.title

app/forms.py
from django import forms
from .models import Comment


class CommentCreateForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = ('text','target',)
        # should not include 'target', otherwise pulldown will be displayed
        fields = ('text',)

app/views.py
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CommentCreateForm
from .models import Diary


def index(request):
    context = {
        'diary_list': Diary.objects.all(),
        'form': CommentCreateForm(),
    }
    return render(request, 'app/diary_list.html', context)


@require_POST
def create_comment(request, pk):
    form = CommentCreateForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.target = get_object_or_404(Diary, pk=pk)
        comment.save()
        return redirect('app:index')
        # 'index' and 'comment_create' is url name

    context = {
        'diary_list': Diary.objects.all(),
        'error_form': form,
        'form': CommentCreateForm(),
    }
    return render(request, 'app/diary_list.html', context)

app/templates/app/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>short_diary</title>
  </head>
  <body>
    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

app/templates/app/diary_list.html
{% extends 'app/base.html' %}

{% block content %}
    {{ error_form.errors }}
    <h1 class="mb-5">My Diary</h1>
    {% for diary in diary_list %}
        {{ diary.text | linebreaksbr }} <span class="text-muted">{{ diary.created_at }}</span>

        <!-- list of comments and comment form -->
        <div class="mt-3 ml-5">
            <!-- comment form for the comment -->
            <form action="{% url 'app:comment_create' diary.pk %}" method="POST">
                <!-- """ 'index' and 'comment_create' is url name """ -->
                {{ form }}
                <button type="submit">Submit</button>
                {% csrf_token %}
            </form>

            <!-- draw comments that are linked to the diary -->
            {% for comment in diary.comment_set.all %}
                {{ comment.text }} <span class="text-muted">{{ diary.created_at }}</span><br>
            {% endfor %}
        </div><!-- end of comment list and comment form -->

        <hr>
    {% endfor %}
{% endblock %}